name: django-blog-project-local
version: '3.0.2'

services:

  db:
    image: postgres:18
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 5s
      timeout: 7s
      retries: 5
      start_period: 10s

  web:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ghcr.io/yourusername/yourrepo:latest
    init: true
    volumes:
      - .:/code
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      db:
        condition: service_healthy
    # develop:  # --watch mode -> development feature
    #   watch:
    #     - action: sync+restart
    #       path: .
    #       target: /code
    #       ignore:
    #         - requirements.txt
    #     - action: rebuild
    #       path: requirements.txt


volumes:
  postgres_data:
